server:
  port: 8080

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: chatter
  datasource:
    url: jdbc:postgresql://localhost:5432/security_users
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always

logging:
  level:
    root: INFO
